; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

; Generated by VC++ for Common Language Runtime
.file "G:\repogitory\hm_javascript\hmJS.src\hmJS\x64\Release\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
